# Git conflicts/merge
# This is done to fix the conflicts between prod and dev git repos.
# Reason: Prod and Dev env are not synchronized.
# Conventionally, `upstream`=prod and `origin`=dev environments.

git fetch upstream
git merge --no-ff upstream/master

git add .....
git commit ...
git tag ...
git push upstream master v.....
